name: zing_call
description: ZegoCloud Web Calling App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # 🔥 Yeh version Flutter 3.5.3 aur Dart SDK ke sath 100% compatible hai 🔥
  zego_uikit_prebuilt_call: ^4.17.13

flutter:
  uses-material-design: true
